# Generated by Django 3.0.3 on 2020-04-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articl_title', models.CharField(max_length=200, verbose_name='Article name')),
                ('articl_text', models.TextField(verbose_name='Article text')),
                ('pub_date', models.DateTimeField(verbose_name='Date of Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_name', models.CharField(max_length=70, verbose_name='Autor name')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Comment text')),
                ('articl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articls.Articl')),
            ],
        ),
    ]
