# Generated by Django 3.0.3 on 2020-09-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_number', models.CharField(max_length=50, verbose_name='Номер заказа')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('oder_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('delivery_date', models.DateTimeField(verbose_name='Дата сдачи')),
                ('sn_number', models.CharField(max_length=50, verbose_name='SN')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('texture1', models.CharField(max_length=50, verbose_name='Текстура1')),
                ('decorator1', models.CharField(max_length=50, verbose_name='Декоратор1')),
                ('status1', models.CharField(max_length=50, verbose_name='Статус1')),
                ('date1', models.DateTimeField(verbose_name='Дата1')),
                ('comment1', models.CharField(max_length=200, verbose_name='Комментарий1')),
                ('texture2', models.CharField(max_length=50, verbose_name='Текстура2')),
                ('decorator2', models.CharField(max_length=50, verbose_name='Декоратор2')),
                ('status2', models.CharField(max_length=50, verbose_name='Статус2')),
                ('date2', models.DateTimeField(verbose_name='Дата2')),
                ('comment2', models.CharField(max_length=200, verbose_name='Комментарий2')),
            ],
        ),
    ]
